### ISSUE TITLE
is_ssl() is not the problem

### ISSUE THREAD

**Issue by DanielRuf** [IshYoBoy/aaa-ishyoboy-google-chrome-44-ssl-fix#3]
https://github.com/WordPress/WordPress/blob/ceec5ac00b406e00d6a0a19be4b1fc20cdf4992d/wp-includes/functions.php#L3748

It never used HTTP_HTTPS

compare it with a commit from January 2015:
https://github.com/WordPress/WordPress/blob/29cd3fa5bf486abb555a5f78541fd14e98a7e938/wp-includes/functions.php#L3672

https://code.google.com/p/chromium/issues/detail?id=505268#c63

https://ma.ttias.be/chrome-44-sending-https-header-by-mistake-breaking-web-applications-everywhere/

> Some PHP code, like the WooCommerce WordPress plugin didn't only check $_SERVER['HTTPS'], but also looked at $_SERVER['HTTP_HTTPS'] to detect HTTPS on the site. This is wrong PHP code and has nothing to do with "bad PHP by design".

**Comment by VlooMan** [comment]
Hey Daniel,

Never said WordPress used "HTTP_HTTPS". Mattias-es article explains it perfectly. Basically if the "HTTP_HTTPS" is set it means the user comes from the affected browser.

For some reason when visitors use the affected browsers on our WebServer the HTTPS is set to "on" and HTTP_HTTPS is set to "1" and the port is "443"; This means using is_ssl() will always return true.

This is why we used this as a check to avoid the HTTPS var being altered in other cases. Only chrome sets "HTTP_HTTPS".

Cheers

**Comment by DanielRuf** [comment]
Well, the readme says somethin different (does not reflect the fact that the HTTPS header field is not affected, just HTTP_HTTPS)

> The latest version of Google Chrome Browser does a very strange thing. It sends HTTPS header with value 1 which the is_ssl() WordPress function reads and sets the HTTPS as TRUE.

When your server uses port 443, it clearly uses SSL. The code in WordPress is not wrong.
Please check your server if there are any misconfigurations. HTTP_HTTPS is never checked by WordPress but some plugins which is a bug in the plugins.

The port comes from your server, also the HTTPS field. Just all HTTP_ prefixed fields come from the client / browser like HTTP_ACCEPT_LANGUAGE, HTTP_HTTPS, ... So there is clearly a misconfiguration with your server.

@tomsommer is right https://github.com/IshYoBoy/aaa-ishyoboy-google-chrome-44-ssl-fix/pull/2#issuecomment-124390012

**Comment by VlooMan** [comment]
The readme never mentions HTTP_HTTPS. The quotation you provided is correct. The information came from the Chromium bug tracker.

Source:
https://code.google.com/p/chromium/issues/detail?id=505268#c37
https://code.google.com/p/chromium/issues/detail?id=501842

I never said the code in WordPress is wrong. It is correct indeed. The problem is that when it does its job it always returns TRUE since the $_SERVER['HTTPS'] is set and 'on'. So if you do not use the function in a plugin or a theme you shouldn't experience any problem. There might be other users experiencing the same.

I contacted the hosting provider to check the server configuration right when the problem started to appear.

Please read the latest update here:
https://ma.ttias.be/chrome-44-sending-https-header-by-mistake-breaking-web-applications-everywhere/

Cheers

**Comment by DanielRuf** [comment]
Again, this is in your readme but not true ;-)

> The latest version of Google Chrome Browser does a very strange thing. It sends HTTPS header with value 1 which the is_ssl() WordPress function reads and sets the HTTPS as TRUE.

is_sssl() is clearly not the problem but plugins like WooCommerce who do not use is_ssl() but check HTTP_HTTPS.

No_ HTTPS is not set to on, just HTTP_HTTPS

I have read the last update already and meant this in my comments.

> Update #1: only HTTP_ prefixed headers are affected.

HTTPS is not affected, just HTTP_HTTPS

**Comment by tomsommer** [comment]
Well, when you force HTTPS to 'off' you break is_ssl() on all sites that actually run SSL. So in some way you are no better than WooCommerce ;)

HTTPS is only affected because WooCommerce fucks it up when  HTTP_HTTPS is set.

**Comment by DanielRuf** [comment]
> Well, when you force HTTPS to 'off' you break is_ssl() on all sites that actually run SSL. So in some way you are no better than WooCommerce ;)

Exactly.

https://github.com/woothemes/woocommerce/issues/8479

**Comment by VlooMan** [comment]
You guys are right.

It seems that on my side the problem was caused by the Hosting provider who incorrectly set the $_SERVER['HTTPS'] based on the existence of $_SERVER['HTTP_HTTPS'] and thus the is_ssl() function always returned TRUE.

I am going to update the readme. And the code. Thank you very much for the cooperation on this!

**Comment by VlooMan** [comment]
Readme file changed. Code updated. You can close this issue if all ok.

**Comment by DanielRuf** [comment]
You are welcome, good that we cleared this.
